spring.rabbitmq.host=gerbil.rmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=ksuvgobu
spring.rabbitmq.password=SzvCV9nXKvff2MqWFUYtutDk7D-L1mSB
spring.rabbitmq.virtual-host=ksuvgobu
spring.rabbitmq.ssl.enabled=true